import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const font = Outfit({
  subsets: ["latin"]
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className} >
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
